[general]
import = [
    "~/.config/alacritty/themes/themes/solarized_light.toml"
]

[[keyboard.bindings]]
chars = "\u0001n"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0001p"
key = "Tab"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[selection]
save_to_clipboard = true

[window]
dynamic_padding = true

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b\r"
